import React, { useEffect, useState } from 'react';
import { CardReworkP4Scaled } from '../cards/CardReworkP4.jsx';
import { CampaignScene, CampaignMotionControl } from './CampaignScene.jsx';
import { CampaignBackdrop, CampaignSigil, CampaignMap, campaignArt, heroArt, encounterKinds } from './CampaignScenery.jsx';
import { CampaignDeparture } from './CampaignDeparture.jsx';
import { CampaignDialog } from './CampaignDialog.jsx';
import { loadCampaignRun, saveCampaignRun } from '../../campaign/state/persistence.js';
import { availableFirstActNodes, firstActReducer, eventChoices, previewFirstActChoice, runCard, runLeague, mature, transformationPool } from '../../campaign/state/firstActState.js';
import { FIRST_ACT_STAGES, firstActNode, firstActCard, POWER_PACKAGES, NASCENTE, campaignField } from '../../campaign/data/firstAct.js';
import { firstActDuelConfig } from '../../campaign/logic/firstActBattle.js';
import '../../styles/campaign/controlled-campaign.css';
const labels = { conserva:'Per ora, ciò che sono basta.', power:'La forza per contendere il terreno. (+1 POT)', damage:'Rendere decisiva una vittoria. (+1 DAN)', evolve:'Rafforza il Potere attuale.', evolvePower:'Rimonta: +2 POT, +1 DAN', evolveDamage:'Rimonta: +1 POT, +2 DAN', liberi:'Liberali. (+3 PV alla prossima battaglia)', trattenuti:'Trattienili. (+2 FC alla prossima battaglia)', comunione:'Lascia parlare i Concordia conservati. (+2 FC e Comunione)' };
export function FirstActHub({ campaignSaveSlot=0, onStartMission, onBack }) {
  const [run,setRun] = useState(()=>loadCampaignRun(campaignSaveSlot));
  const [error,setError] = useState(''), [army,setArmy]=useState(false), [selected,setSelected]=useState(null), [choice,setChoice]=useState(null), [family,setFamily]=useState(null), [inspect,setInspect]=useState(false);
  const [mapPage,setMapPage] = useState(()=>Math.floor((run?.stage || 0)/6)), [departure,setDeparture]=useState(null);
  useEffect(()=>setMapPage(Math.min(2,Math.floor((run?.stage || 0)/6))),[run?.stage]);
  const [draft,setDraft]=useState(run?.deck || []);
  if (!run) return <section className="campaign-control"><p>Salvataggio non leggibile.</p><button onClick={onBack}>Menu</button></section>;
  const commit = action => {
    try { const next=firstActReducer(run,action); if(!saveCampaignRun(next,campaignSaveSlot)) throw new Error('Salvataggio non riuscito: nessuna azione confermata.'); setRun(next);setDraft(next.deck);setError('');return next; }
    catch(e){setError(e.message);return null;}
  };
  const available=availableFirstActNodes(run), node=available.find(n=>n.id===selected)||available[0];
  const start = () => { const next=run.active ? run : commit({type:'START',nodeId:node.id});if(!next)return; const n=firstActNode(next.active.nodeId);setDeparture({mission:{...n,enemy:{army:n.army,deck:n.roster},campaignAttempt:next.active.id,campaignPhase:next.active.phase},run:next}); };
  const enterDuel=()=>{try{onStartMission(departure.mission,departure.run);}catch(e){setError(e.message);}finally{setDeparture(null);}};
  const openArmy=()=>{setDraft(run.deck);setArmy(true);};
  const options=eventChoices(run);
  let preview=null,previewError='';
  if(choice)try{preview=previewFirstActChoice(run,choice);}catch(e){previewError=e.message;}
  const nextCard=preview ? runCard(preview,NASCENTE) : null;
  const battleNode=run.active ? firstActNode(run.active.nodeId) : node;
  const enemy=battleNode?.roster || [];
  const nascente=runCard(run,NASCENTE);
  const mapRun={stageIndex:run.stage,outcome:run.outcome,definition:{events:[]},history:run.history.map(h=>({...h,missionId:h.nodeId}))};
  const mapAct={stages:FIRST_ACT_STAGES.slice(mapPage*6,mapPage*6+6).map(ids=>({alternatives:ids.map(firstActNode)}))};
  const resources=battleNode?.kind!=='event' && battleNode ? firstActDuelConfig({...run,active:run.active || {nodeId:battleNode.id,phase:0,playerSquads:[run.deck.slice(0,5)],enemySquads:[battleNode.roster.slice(0,5)],opening:[true]}}).campaignDuelMod : null;
  return <CampaignScene><CampaignBackdrop/><div className="cs-content">
    <header className="cs-hud"><div className="cs-brand"><CampaignSigil kind="sun"/><div><span className="cs-kicker">SATZE · ATTO I</span><strong>Oltre il Vallo</strong></div></div><nav className="cs-actions"><button onClick={openArmy}>Armata e riserva</button><CampaignMotionControl/><button onClick={onBack}>Menu</button></nav></header>
    <div className="cs-act-heading"><div><p className="cs-kicker">IL CAMMINO DEL NASCENTE</p><h1>Oltre il Vallo</h1></div><p>{run.completed} tappe completate · {run.slots} posti · Lega {runLeague(run)}/30</p></div>
    {error&&<p className="cs-error" role="alert">{error}</p>}
    {run.outcome ? <section className="cs-ending"><img src={heroArt(nascente)} alt="Il Nascente"/><div><h2>Il Vallo è alle tue spalle</h2><p>Hai completato il primo atto. Il Nascente e la tua riserva conservano il cammino compiuto.</p><button className="cs-primary" onClick={onBack}>Torna al menu</button></div></section> : run.pendingReward ? <section className="cs-encounter cs-first-reward-panel"><div className="cs-encounter-body"><h2>Gli agenti dello sconfitto</h2><p>{run.pendingReward.offer.length===1?'Hai ottenuto questo agente.':'Scegli un agente fra i due prigionieri.'} Un’identità già posseduta resta in riserva come copia separata.</p><div className="cs-first-rewards">{run.pendingReward.offer.map(id=><button key={id} onClick={()=>commit({type:'REWARD',cardId:id})}><CardReworkP4Scaled agent={firstActCard(id)} width={180}/><span>Accogli {firstActCard(id).name}</span></button>)}</div></div></section> : run.pendingEvent ? <section className="cs-event"><div className="cs-event-portrait"><img src={heroArt(nascente)} alt="Il Nascente"/><CampaignSigil kind="special"/></div><div className="cs-event-body"><p className="cs-kicker">EVENTO</p><h2>{firstActNode(run.pendingEvent.id).title}</h2><p>{run.pendingEvent.id==='E06'?'Hanno deposto le armi. Le campane continuano a suonare.':'Su cosa vuoi fondare la forza che porterai oltre il Vallo?'}</p>
      <div className="cs-first-options">{options.filter(id=>labels[id]).map(id=><button key={id} aria-pressed={choice===id} onClick={()=>{setChoice(id);setFamily(null);}}>{labels[id]}</button>)}</div>
      {options.some(id=>POWER_PACKAGES.some(p=>p.id===id))&&<><h3>{run.nascente.packageId?'Dai una nuova forma al tuo Potere':'Cerca la tua risposta'}</h3><div className="cs-first-options">{[...new Set(POWER_PACKAGES.map(p=>p.family))].map(f=><button key={f} aria-pressed={family===f} onClick={()=>{setFamily(f);setChoice(null);}}>{f}</button>)}</div>{family&&<div className="cs-first-options"><h4>Come traduci questa convinzione in battaglia?</h4>{POWER_PACKAGES.filter(p=>p.family===family).map(p=><button key={p.id} aria-pressed={choice===p.id} onClick={()=>setChoice(p.id)}>{p.answer}</button>)}</div>}</>}
      {previewError&&<p role="alert">{previewError}</p>}{preview&&<div className="cs-first-preview"><CardReworkP4Scaled agent={nextCard} width={180}/><div><p>{nextCard.description}</p><p>Lega esercito dopo la scelta: {runLeague(preview)}/30</p><button className="cs-primary" onClick={()=>{if(commit({type:'CHOICE',choice})){setChoice(null);setFamily(null);}}}>Conferma risposta</button></div></div>}
    </div></section> : <div className="cs-world-layout"><div className="cs-first-cartography">
      <nav className="cs-map-pages" aria-label="Sezioni del percorso">{[0,1,2].map(page=><button key={page} aria-pressed={mapPage===page} onClick={()=>setMapPage(page)}>Tappe {page*6+1}–{Math.min((page+1)*6,FIRST_ACT_STAGES.length)}{Math.floor(run.stage/6)===page?' · Sei qui':''}</button>)}</nav>
      <CampaignMap act={mapAct} run={mapRun} stageOffset={mapPage*6} availableIds={available.map(n=>n.id)} interactionLocked={!!run.active} selectedId={battleNode?.id} onSelect={setSelected} legend="Bivi, Domande e Faglie lungo il cammino"/>
    </div><aside className={`cs-encounter cs-kind-${battleNode?.kind}`} aria-label="Incontro selezionato">
      <div className="cs-encounter-art"><img src={battleNode?.kind==='event'?heroArt(nascente):battleNode?.kind==='faglia'?`${import.meta.env.BASE_URL}card-images/agents/${enemy[0]}.webp`:campaignArt} alt={battleNode?.army || 'Il Nascente'}/><span className="cs-encounter-type"><CampaignSigil kind={battleNode?.kind}/>{encounterKinds[battleNode?.kind]}</span></div><div className="cs-encounter-body">
      <p className="cs-kicker">{battleNode?.kind==='faglia'?'FAGLIA · INCURSIONE':battleNode?.kind==='event'?'DOMANDA':battleNode?.kind==='boss'?'BOSS · DUE SQUADRE':battleNode?.kind==='elite'?'ÉLITE':'SCONTRO'}</p><h2>{battleNode?.title}</h2>
      {run.active ? <><p>Fase {run.active.phase+1} di {run.active.enemySquads.length}. Il tentativo è conservato.</p><button className="cs-primary" onClick={start}>{run.active.snapshot?'Riprendi lo scontro':run.active.phase?'Affronta la seconda squadra':'Entra nello scontro'}</button><button onClick={()=>commit({type:'ABANDON'})}>Abbandona il tentativo</button></> : node?.kind==='event' ? <button className="cs-primary" onClick={()=>commit({type:'ENTER_EVENT'})}>Ascolta la domanda</button> : <>
      <p>{node?.kind==='faglia'?'Una deformazione dello spazio apre il passaggio a un’armata guidata da un altro Giocatore. Affronti la sua incursione.':node?.army}</p><p>{node?.size} agenti per esercito · {Math.min(5,node?.size)} in mano</p><p>Tu: {resources?.playerLife} PV / {resources?.playerFocus} FC<br/>Nemico: {resources?.enemyLife} PV / {resources?.enemyFocus} FC</p>{resources?.plan&&<p>{resources.plan==='assalto'?'Assalto: primo DAN nemico +1.':'Tenuta: primo DAN subito dal nemico −1 (min 0).'}</p>}
      {node?.id==='I1'&&<p className="cs-tutorial-note">La Picca apre lo scontro. Impegna i tuoi 10 FC: a pari VA, Lega e POT prevale chi gioca per secondo.</p>}
      {node?.plan&&<p>Vincendo interrompi il piano {({riserve:'Corazze',corazze:'Riserve',tenuta:'Assalto',assalto:'Tenuta'})[node.plan]}. Nei successivi scontri Concordia resterà {({riserve:'Riserve: +2 FC nemici',corazze:'Corazze: +2 PV nemici',tenuta:'Tenuta: primo DAN nemico subito −1',assalto:'Assalto: primo DAN nemico inflitto +1'})[node.plan]}.</p>}<p>{node?.winRule==='varco'?'Conquista Il primo varco per vincere.':node?.winRule==='territory'?'A mano esaurita: più Campi, poi più PV.':'Duello Classico: conquista i Campi o annienta il nemico.'}</p><button onClick={()=>setInspect(true)}>Esamina armata e Campi</button>
      {run.lastResult&&<p>{run.lastResult==='draw'?'Pareggio.':'Sconfitta.'} Puoi riorganizzare l’esercito e ritentare.</p>}
      <button className="cs-primary" onClick={start}>Affronta l’incontro</button>{node?.optional&&<button onClick={()=>{commit({type:'SKIP'});setSelected(null);}}>Prosegui verso la breccia</button>}{run.lastResult==='enemy'&&<button onClick={()=>{if(commit({type:'REWIND'}))setSelected(null);}}>Riavvolgi tre tappe</button>}</>}
    </div></aside></div>}
    <footer className="cs-party">
      <button className="cs-hero-summary" onClick={openArmy}><img src={heroArt(nascente)} alt=""/><div><span className="cs-kicker">IL TUO NASCENTE</span><strong>{nascente.power} POT <i> / </i>{nascente.damage} DAN <i> · </i> L{nascente.league}</strong><small>{nascente.description}</small></div></button>
      <button className="cs-party-deck" onClick={openArmy} aria-label="Gestisci le carte dell’armata"><span className="cs-deck-fan" aria-hidden="true">{run.deck.filter(id=>id!==NASCENTE).slice(0,5).map((id,i)=><img key={id} src={`${import.meta.env.BASE_URL}card-images/agents/${id}.webp`} alt="" style={{'--fan-index':i}}/>)}</span><span><strong>Armata dell’Orizzonte</strong><small>{run.deck.length} carte · Lega {runLeague(run)}/30 · {run.copies.length} copie conservate</small></span><b>→</b></button>
    </footer>
  </div>
  {departure&&<CampaignDeparture mission={departure.mission} onReady={enterDuel}/>}
  {inspect&&<CampaignDialog title="Ricognizione" onClose={()=>setInspect(false)}><div className="cs-first-options">{node.fieldIds.map((id,i)=><p key={i}>{campaignField(id).name} · round {node.revealRounds[i]}<br/>{campaignField(id).description||campaignField(id).effect}</p>)}</div>{node.required?.length>0&&<p>Agenti garantiti nella mano nemica: {node.required.map(id=>firstActCard(id).name).join(', ')}.</p>}{node.squads&&node.squads.map((s,i)=><p key={i}>Squadra {i+1}: {s.map(id=>firstActCard(id).name).join(', ')}.</p>)}<div className="cs-enemy-roster">{enemy.map(id=><CardReworkP4Scaled key={id} agent={firstActCard(id)} width={176}/>)}</div></CampaignDialog>}
  {army&&<CampaignDialog title="Armata e riserva" onClose={()=>setArmy(false)}><p>{draft.length}/{run.slots} agenti · Lega {runLeague(run,draft)}/30. Una sola copia per identità nell’esercito.</p><div className="cs-card-roster">{[NASCENTE,...new Set(run.copies.map(c=>c.cardId))].map(id=><label key={id} className={draft.includes(id)?'selected':''}><input type="checkbox" checked={draft.includes(id)} disabled={id===NASCENTE||!!run.active||!!run.pendingReward} onChange={e=>setDraft(e.target.checked?[...draft,id]:draft.filter(x=>x!==id))}/><div className="cs-roster-card"><CardReworkP4Scaled agent={runCard(run,id)} width={176}/></div><span>{draft.includes(id)?'Schierato nell’armata':'In riserva'}</span></label>)}</div><button className="cs-primary" disabled={!!run.active||!!run.pendingReward} onClick={()=>{if(commit({type:'SET_DECK',deck:draft}))setArmy(false);}}>Salva armata</button><h3>Copie conservate</h3>{run.copies.map(c=><div className="cs-first-copy" key={c.uid}><span>{firstActCard(c.cardId).name} · {mature(run,c)?'Matura':'Completa una tappa successiva'}</span><button disabled={!!run.active||!!run.pendingEvent||!!run.pendingReward||!transformationPool(run,c.uid).length} onClick={()=>commit({type:'TRANSFORM',uid:c.uid})}>Trasforma in un Figlio casuale di pari Lega</button></div>)}</CampaignDialog>}
  </CampaignScene>;
}
