// ============================================
// EMINENZE — Costanti e vocabolario delle primitive
// Fonte normativa: Documentazione/SATZE_EMINENZE_SPEC_UNIFICATA_v2.2.md
// ============================================

/**
 * Gate semantici di reveal (spec §3.2).
 * Non sono fasi cronologiche fisse: sono barriere poste prima di una decisione.
 */
export const REVEAL_GATES = {
  PRE_FIELD: 'PRE_FIELD',
  PRE_AGENT: 'PRE_AGENT',
  GENERAL: 'GENERAL',
};

export const ALL_REVEAL_GATES = [
  REVEAL_GATES.PRE_FIELD,
  REVEAL_GATES.PRE_AGENT,
  REVEAL_GATES.GENERAL,
];

/**
 * Ordini di attraversamento dei gate.
 * L'ordine reale dipende dall'ordine delle decisioni dello Scontro, non dal gate in sé:
 * lo Statico di Mascarada rende pubblici gli Agenti prima del Campo (spec §3.4).
 */
export const GATE_SEQUENCES = {
  FIELD_FIRST: [REVEAL_GATES.PRE_FIELD, REVEAL_GATES.PRE_AGENT, REVEAL_GATES.GENERAL],
  AGENTS_FIRST: [REVEAL_GATES.PRE_AGENT, REVEAL_GATES.PRE_FIELD, REVEAL_GATES.GENERAL],
};

/** Momento in cui i parametri/bersagli di un'abilità vengono fissati (spec §3.6). */
export const CHOICE_PARAMS_TIMING = {
  AT_SELECTION: 'AT_SELECTION',
  AT_REVEAL: 'AT_REVEAL',
};

/**
 * Checkpoint di risoluzione dei segmenti (spec §3.7).
 * `revealGate` ed `effectTiming` sono due cose diverse: un'abilità può rivelarsi al GENERAL
 * e depositare un override che opera più tardi, dentro il Duello.
 *
 * `ROUND_START` precede la prima decisione del round ed è quindi l'unico checkpoint
 * raggiungibile da uno Statico che debba alterare il Campo o l'ordine delle scelte: ciò che
 * modifica le premesse di una decisione deve essere pubblico prima che la decisione avvenga.
 */
export const EFFECT_TIMINGS = {
  ROUND_START: 'ROUND_START',
  AFTER_REVEAL: 'AFTER_REVEAL',
  BEFORE_FIELD_RESOLUTION: 'BEFORE_FIELD_RESOLUTION',
  BEFORE_TRIGGER_CHECK: 'BEFORE_TRIGGER_CHECK',
  BEFORE_POWER_RESOLUTION: 'BEFORE_POWER_RESOLUTION',
  AFTER_DUEL_OUTCOME: 'AFTER_DUEL_OUTCOME',
  BEFORE_CONQUEST: 'BEFORE_CONQUEST',
  POST_BATTLE: 'POST_BATTLE',
  END_ROUND: 'END_ROUND',
  END_MATCH: 'END_MATCH',
  ON_HP_LOSS: 'ON_HP_LOSS',
};

export const EFFECT_TIMING_ORDER = [
  EFFECT_TIMINGS.ROUND_START,
  EFFECT_TIMINGS.AFTER_REVEAL,
  EFFECT_TIMINGS.BEFORE_FIELD_RESOLUTION,
  EFFECT_TIMINGS.BEFORE_TRIGGER_CHECK,
  EFFECT_TIMINGS.BEFORE_POWER_RESOLUTION,
  EFFECT_TIMINGS.AFTER_DUEL_OUTCOME,
  EFFECT_TIMINGS.BEFORE_CONQUEST,
  EFFECT_TIMINGS.POST_BATTLE,
  EFFECT_TIMINGS.END_ROUND,
  EFFECT_TIMINGS.END_MATCH,
  EFFECT_TIMINGS.ON_HP_LOSS,
];

/** Stato del formato rispetto al sottosistema Eminenza (spec §1.2). */
export const EMINENCE_FORMAT = {
  REQUIRED: 'required',
  DISABLED: 'disabled',
};

/** Numero minimo di carte di un'Armata perché la sua Eminenza sia eleggibile (spec §1.2). */
export const EMINENCE_ELIGIBILITY_THRESHOLD = 5;

/**
 * Vocabolario delle primitive del motore.
 *
 * Regola architetturale: il motore conosce soltanto queste primitive. Una singola Eminenza
 * non deve mai comparire come ramo condizionale nel motore; è una configurazione costruita
 * sopra questo vocabolario.
 */
export const EMINENCE_PRIMITIVES = {
  CHANGE_PRESENCE: 'CHANGE_PRESENCE',
  MODIFY_STAT: 'MODIFY_STAT',
  LOSE_HP: 'LOSE_HP',
  HEAL_HP: 'HEAL_HP',
  IGNORE_FIELD: 'IGNORE_FIELD',
  FORCE_TRIGGER: 'FORCE_TRIGGER',
  FORBID_TRIGGER: 'FORBID_TRIGGER',
  REPLACE_TRIGGER: 'REPLACE_TRIGGER',
  ALIAS_TRIGGER: 'ALIAS_TRIGGER',
  UNBLOCKABLE_POWER: 'UNBLOCKABLE_POWER',
  SUPPRESS_CONQUEST: 'SUPPRESS_CONQUEST',
  GRANT_TEMPORARY_FOCUS: 'GRANT_TEMPORARY_FOCUS',
  MODIFY_LEAGUE: 'MODIFY_LEAGUE',
  SET_ARMY_BONUS_STATE: 'SET_ARMY_BONUS_STATE',
  APPLY_SLOT_MODIFIER: 'APPLY_SLOT_MODIFIER',
  REPLACE_FIELD: 'REPLACE_FIELD',
  DESTROY_FIELD: 'DESTROY_FIELD',
  APPLY_TOXIN: 'APPLY_TOXIN',
  MARK_CARD: 'MARK_CARD',
  COMPOSE_ABILITY: 'COMPOSE_ABILITY',
  REGISTER_END_MATCH_DEBT: 'REGISTER_END_MATCH_DEBT',
  BLOCK_EMINENCE: 'BLOCK_EMINENCE',
  MODIFY_ANCHORED_THRESHOLD: 'MODIFY_ANCHORED_THRESHOLD',
  ADJUST_ABILITY_COST: 'ADJUST_ABILITY_COST',
  CONVERT_STAT: 'CONVERT_STAT',
  ARM_CONQUEST_OVERRIDE: 'ARM_CONQUEST_OVERRIDE',
  SYNC_TRIGGERS_ON_XOR: 'SYNC_TRIGGERS_ON_XOR',
  SATISFY_TRIGGER_ON_EQUAL_LEAGUE: 'SATISFY_TRIGGER_ON_EQUAL_LEAGUE',
  ARM_VA_TIE_WIN: 'ARM_VA_TIE_WIN',
  GRANT_POWER: 'GRANT_POWER',
};

/**
 * Origini dinamiche per `paramsSchema`. Il catalogo dichiara la fonte; la vista della
 * scelta la materializza sullo stato persistente pubblico (es. gli id già marcati).
 */
export const PARAM_SOURCES = {
  OWN_FRAGMENTS: 'OWN_FRAGMENTS',
  ENEMY_UNDEPLOYED: 'ENEMY_UNDEPLOYED',
  UNDEPLOYED_AGENTS: 'UNDEPLOYED_AGENTS',
  OWN_UNDEPLOYED: 'OWN_UNDEPLOYED',
  CONFIRMED_AGENTS: 'CONFIRMED_AGENTS',
  BATTLEFIELD_SLOTS: 'BATTLEFIELD_SLOTS',
};

/** Bersagli ammessi dalle primitive. */
export const PRIMITIVE_TARGETS = {
  SELF: 'SELF',
  OPPONENT: 'OPPONENT',
  OWN_AGENT: 'OWN_AGENT',
  ENEMY_AGENT: 'ENEMY_AGENT',
  BOTH: 'BOTH',
  GLOBAL: 'GLOBAL',
  CHOSEN: 'CHOSEN',
};

/**
 * Target ammessi per primitiva. `null` nella lista = il segmento può omettere `target`
 * (parametri, scope, o side-effect globale). Un target presente deve comunque essere
 * in `PRIMITIVE_TARGETS`.
 */
export const PRIMITIVE_ALLOWED_TARGETS = {
  [EMINENCE_PRIMITIVES.CHANGE_PRESENCE]: [
    PRIMITIVE_TARGETS.SELF,
    PRIMITIVE_TARGETS.OPPONENT,
    PRIMITIVE_TARGETS.BOTH,
  ],
  [EMINENCE_PRIMITIVES.MODIFY_STAT]: [
    PRIMITIVE_TARGETS.OWN_AGENT,
    PRIMITIVE_TARGETS.ENEMY_AGENT,
    PRIMITIVE_TARGETS.BOTH,
    PRIMITIVE_TARGETS.CHOSEN,
  ],
  [EMINENCE_PRIMITIVES.LOSE_HP]: [
    PRIMITIVE_TARGETS.SELF,
    PRIMITIVE_TARGETS.OPPONENT,
    PRIMITIVE_TARGETS.BOTH,
    PRIMITIVE_TARGETS.CHOSEN,
  ],
  [EMINENCE_PRIMITIVES.HEAL_HP]: [
    PRIMITIVE_TARGETS.SELF,
    PRIMITIVE_TARGETS.OPPONENT,
    PRIMITIVE_TARGETS.BOTH,
    PRIMITIVE_TARGETS.CHOSEN,
  ],
  [EMINENCE_PRIMITIVES.IGNORE_FIELD]: [
    PRIMITIVE_TARGETS.OWN_AGENT,
    PRIMITIVE_TARGETS.ENEMY_AGENT,
    PRIMITIVE_TARGETS.BOTH,
  ],
  [EMINENCE_PRIMITIVES.FORCE_TRIGGER]: [null],
  [EMINENCE_PRIMITIVES.FORBID_TRIGGER]: [null],
  [EMINENCE_PRIMITIVES.REPLACE_TRIGGER]: [null],
  [EMINENCE_PRIMITIVES.ALIAS_TRIGGER]: [null],
  [EMINENCE_PRIMITIVES.UNBLOCKABLE_POWER]: [null],
  [EMINENCE_PRIMITIVES.SUPPRESS_CONQUEST]: [null],
  [EMINENCE_PRIMITIVES.GRANT_TEMPORARY_FOCUS]: [
    PRIMITIVE_TARGETS.OWN_AGENT,
    PRIMITIVE_TARGETS.ENEMY_AGENT,
    PRIMITIVE_TARGETS.CHOSEN,
    PRIMITIVE_TARGETS.BOTH,
  ],
  [EMINENCE_PRIMITIVES.MODIFY_LEAGUE]: [
    PRIMITIVE_TARGETS.OWN_AGENT,
    PRIMITIVE_TARGETS.ENEMY_AGENT,
    PRIMITIVE_TARGETS.CHOSEN,
  ],
  [EMINENCE_PRIMITIVES.SET_ARMY_BONUS_STATE]: [
    PRIMITIVE_TARGETS.SELF,
    PRIMITIVE_TARGETS.OWN_AGENT,
    PRIMITIVE_TARGETS.OPPONENT,
    PRIMITIVE_TARGETS.BOTH,
  ],
  [EMINENCE_PRIMITIVES.APPLY_SLOT_MODIFIER]: [null],
  [EMINENCE_PRIMITIVES.REPLACE_FIELD]: [PRIMITIVE_TARGETS.GLOBAL, null],
  [EMINENCE_PRIMITIVES.DESTROY_FIELD]: [null],
  [EMINENCE_PRIMITIVES.APPLY_TOXIN]: [
    PRIMITIVE_TARGETS.OPPONENT,
    PRIMITIVE_TARGETS.ENEMY_AGENT,
    PRIMITIVE_TARGETS.SELF,
    PRIMITIVE_TARGETS.CHOSEN,
  ],
  [EMINENCE_PRIMITIVES.MARK_CARD]: [
    PRIMITIVE_TARGETS.OWN_AGENT,
    PRIMITIVE_TARGETS.ENEMY_AGENT,
    PRIMITIVE_TARGETS.CHOSEN,
    null,
  ],
  [EMINENCE_PRIMITIVES.COMPOSE_ABILITY]: [
    PRIMITIVE_TARGETS.OWN_AGENT,
    PRIMITIVE_TARGETS.CHOSEN,
    null,
  ],
  [EMINENCE_PRIMITIVES.REGISTER_END_MATCH_DEBT]: [null],
  [EMINENCE_PRIMITIVES.BLOCK_EMINENCE]: [
    PRIMITIVE_TARGETS.SELF,
    PRIMITIVE_TARGETS.OPPONENT,
    PRIMITIVE_TARGETS.BOTH,
  ],
  [EMINENCE_PRIMITIVES.MODIFY_ANCHORED_THRESHOLD]: [
    PRIMITIVE_TARGETS.SELF,
    PRIMITIVE_TARGETS.OPPONENT,
    PRIMITIVE_TARGETS.BOTH,
  ],
  [EMINENCE_PRIMITIVES.ADJUST_ABILITY_COST]: [null],
  [EMINENCE_PRIMITIVES.CONVERT_STAT]: [
    PRIMITIVE_TARGETS.OWN_AGENT,
    PRIMITIVE_TARGETS.ENEMY_AGENT,
    PRIMITIVE_TARGETS.CHOSEN,
  ],
  [EMINENCE_PRIMITIVES.ARM_CONQUEST_OVERRIDE]: [null],
  [EMINENCE_PRIMITIVES.SYNC_TRIGGERS_ON_XOR]: [null],
  [EMINENCE_PRIMITIVES.SATISFY_TRIGGER_ON_EQUAL_LEAGUE]: [null],
  [EMINENCE_PRIMITIVES.ARM_VA_TIE_WIN]: [null],
  [EMINENCE_PRIMITIVES.GRANT_POWER]: [
    PRIMITIVE_TARGETS.OWN_AGENT,
    PRIMITIVE_TARGETS.ENEMY_AGENT,
    PRIMITIVE_TARGETS.CHOSEN,
  ],
};

/** Ambito di applicazione delle primitive che agiscono sui trigger. */
export const TRIGGER_SCOPES = {
  OWN: 'OWN',
  ENEMY: 'ENEMY',
  GLOBAL: 'GLOBAL',
};

/** Cause di perdita PV distinguibili (spec §10.1). */
export const HP_LOSS_CAUSES = {
  DUEL_DEFEAT_DAMAGE: 'DUEL_DEFEAT_DAMAGE',
  DIRECT_DAMAGE: 'DIRECT_DAMAGE',
  SELF_DAMAGE: 'SELF_DAMAGE',
  TOXIN: 'TOXIN',
  EMINENCE_COST: 'EMINENCE_COST',
  DEBT: 'DEBT',
  END_MATCH_DEBT: 'END_MATCH_DEBT',
  OTHER: 'OTHER',
};

/** Lati del duello, usati come chiavi stabili nello stato. */
export const SIDES = {
  PLAYER: 'player',
  ENEMY: 'enemy',
};

export const OPPOSITE_SIDE = {
  [SIDES.PLAYER]: SIDES.ENEMY,
  [SIDES.ENEMY]: SIDES.PLAYER,
};
